global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: bentoml_service
    metrics_path: "/metrics"
    static_configs:
      - targets: ["localhost:3000"]

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]